name: HTTP Request Action
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: GET request
      id: getrequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://community-app-topaz.vercel.app/api/events/'
        method: 'GET'
    - name: Show Response
      run: |
        echo ${{ steps.getrequest.outputs.response[0] }}
            
